<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BNIRTNQ" failures="1" tests="4" name="Test" time="60.939" errors="0" timestamp="2023-01-03T21:49:40 IST">
  <testcase classname="com.sauceDemo.TestPackage.TC01_VerifyLoginFunctionality" name="verifyLoginFunctionality" time="0.077"/>
  <testcase classname="com.sauceDemo.TestPackage.TC02_VerifyLogOutFunctionality" name="verifyLogOutFunctionality" time="1.698"/>
  <testcase classname="com.sauceDemo.TestPackage.TC03_VerifyBagProductAddToCartFunctionality" name="verifyBagProductAddToCartFunctionality" time="0.615"/>
  <testcase classname="com.sauceDemo.TestPackage.TC04_VerifyAllProductsAddToCart_Functionality" name="verifyAllProductsAddToCartFunctionality" time="1.376">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.sauceDemo.TestPackage.TC04_VerifyAllProductsAddToCart_Functionality.verifyAllProductsAddToCartFunctionality(TC04_VerifyAllProductsAddToCart_Functionality.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyAllProductsAddToCartFunctionality -->
</testsuite> <!-- Test -->
